import type { Metadata } from "next";
import { Poppins, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight:["400", "500", "600", "700",],
  display:"swap",
});


const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Richard Hodáň",
  description: "Generated by Richard Hodáň",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className= {`${poppins.variable} ${openSans.variable} antialiased font-sans`}
      >
        
        <Header/>
        
        {children}
        
        <Footer/>
        
      </body>
    </html>
  );
}

